source 'https://rubygems.org'
gemspec name: 'firespring_dev_commands'

gem 'builder', '~> 3.2.4'
gem 'bundler-audit', '~> 0.9.1'
gem 'launchy', '~> 2.5.2'
gem 'rspec', '~> 3.12.0'
gem 'rubocop', '~> 1.54.1'
gem 'rubocop-performance', '~> 1.18.0'
gem 'rubocop-rake', '~> 0.6.0'
gem 'simplecov', '~> 0.22.0'
gem 'yard', '~> 0.9.34'
